const HTTP_METHODS = {
    POST: "POST",
    GET: "GET",
};

const HTTP_ERROR_CODES = {
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    INTERNAL_SERVER_ERROR: 500,
}

module.exports = { HTTP_ERROR_CODES, HTTP_METHODS };

